apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
  namespace: hospital-ns
type: Opaque
stringData:
  SESSION_SECRET: hospital-secret-key-2024-change-this-in-production
  JWT_SECRET: jwt-secret-key-hospital-2024-change-this-in-production
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin123