apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-tracker-app
  namespace: hospital-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-tracker-app
  template:
    metadata:
      labels:
        app: hospital-tracker-app
    spec:
      containers:
        - name: hospital-app
          image: pavithrasambath2003/hospital:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
    
